name: ptolemay_test_project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Functional programming thingies
  dartz: ^0.10.1

  # Bloc / Cubit for state management
  flutter_bloc: 7.0.1

  # Value equality
  equatable: ^2.0.0

  # Remote API
  dio: ^4.0.6

  # Local cache
  cached_network_image: ^3.0.0

  # DI
  get_it: ^7.1.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

